//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almwdeh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralInformationTbl
    {
        public int Id { get; set; }
        public string GmailName { get; set; }
        public string GmailEmail { get; set; }
        public string GmailPassword { get; set; }
    }
}
