//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almwdeh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessagesTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessagesTbl()
        {
            this.MessageAttachmentsTbls = new HashSet<MessageAttachmentsTbl>();
            this.MessagesTbl1 = new HashSet<MessagesTbl>();
        }
    
        public int Id { get; set; }
        public string Subject { get; set; }
        public string MessageBody { get; set; }
        public Nullable<int> SenderUserAccessIDs { get; set; }
        public Nullable<int> ReceiverUserAccessIDs { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<int> MessageStatues { get; set; }
        public Nullable<int> ReplyToMessageIDs { get; set; }
        public Nullable<bool> HasAttachments { get; set; }
        public Nullable<bool> HasBeenRead { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageAttachmentsTbl> MessageAttachmentsTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessagesTbl> MessagesTbl1 { get; set; }
        public virtual MessagesTbl MessagesTbl2 { get; set; }
        public virtual UsersAccessTbl UsersAccessTbl { get; set; }
        public virtual UsersAccessTbl UsersAccessTbl1 { get; set; }
    }
}
