//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almwdeh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlmawadehDbEntities : DbContext
    {
        public AlmawadehDbEntities()
            : base("name=AlmawadehDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComboAcademicDegree> ComboAcademicDegrees { get; set; }
        public virtual DbSet<ComboCityIranTbl> ComboCityIranTbls { get; set; }
        public virtual DbSet<ComboCitySyriaTbl> ComboCitySyriaTbls { get; set; }
        public virtual DbSet<ComboDoctrineTbl> ComboDoctrineTbls { get; set; }
        public virtual DbSet<ComboFieldOfStudy> ComboFieldOfStudies { get; set; }
        public virtual DbSet<ComboFinancialStatu> ComboFinancialStatus { get; set; }
        public virtual DbSet<ComboGraduationStatue> ComboGraduationStatues { get; set; }
        public virtual DbSet<ComboScholarshipGroup> ComboScholarshipGroups { get; set; }
        public virtual DbSet<ComboTheIdentifier> ComboTheIdentifiers { get; set; }
        public virtual DbSet<ComboUniversityName> ComboUniversityNames { get; set; }
        public virtual DbSet<GeneralInformationTbl> GeneralInformationTbls { get; set; }
        public virtual DbSet<MessageAttachmentsTbl> MessageAttachmentsTbls { get; set; }
        public virtual DbSet<MessagesTbl> MessagesTbls { get; set; }
        public virtual DbSet<StudentsTbl> StudentsTbls { get; set; }
        public virtual DbSet<StudentsUniversitiesSemestersTbl> StudentsUniversitiesSemestersTbls { get; set; }
        public virtual DbSet<StudentsUniversitiesTbl> StudentsUniversitiesTbls { get; set; }
        public virtual DbSet<UsersAccessTbl> UsersAccessTbls { get; set; }
        public virtual DbSet<UsersRolesTbl> UsersRolesTbls { get; set; }
        public virtual DbSet<ComboShahidRelationship> ComboShahidRelationships { get; set; }
        public virtual DbSet<ComboSkille> ComboSkilles { get; set; }
    }
}
