//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almwdeh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsUniversitiesTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentsUniversitiesTbl()
        {
            this.StudentsUniversitiesSemestersTbls = new HashSet<StudentsUniversitiesSemestersTbl>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserAccessIDs { get; set; }
        public string AcademicDegree { get; set; }
        public string UniversityName { get; set; }
        public string FieldOfStudy { get; set; }
        public string StudentUniversityNumber { get; set; }
        public Nullable<System.DateTime> StartAcademicYearDate { get; set; }
        public string GraduationStatues { get; set; }
        public Nullable<System.DateTime> GraduationYear { get; set; }
        public Nullable<double> AverageScore { get; set; }
        public Nullable<double> AverageScoreAuto { get; set; }
        public string CertificateFile { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<bool> EditVerified { get; set; }
    
        public virtual StudentsTbl StudentsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsUniversitiesSemestersTbl> StudentsUniversitiesSemestersTbls { get; set; }
    }
}
