//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almwdeh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsUniversitiesSemestersTbl
    {
        public int Id { get; set; }
        public Nullable<int> StudentUniversityIDs { get; set; }
        public string SemesterNumber { get; set; }
        public Nullable<double> CreditAchieved { get; set; }
        public Nullable<double> AverageScore { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<bool> EditVerified { get; set; }
    
        public virtual StudentsUniversitiesTbl StudentsUniversitiesTbl { get; set; }
    }
}
