//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almwdeh.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Almwdeh.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء حساب.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطا في إضافة الحساب.
        /// </summary>
        public static string CreateAccountdbSaveChange {
            get {
                return ResourceManager.GetString("CreateAccountdbSaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني مسجلا مسبقا قم بتسجيل الدخول مجددا .
        /// </summary>
        public static string CreateAccountEmailAlreadyExist {
            get {
                return ResourceManager.GetString("CreateAccountEmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء حساب جديد بنجاح.
        /// </summary>
        public static string CreateAccountSuccessfull {
            get {
                return ResourceManager.GetString("CreateAccountSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في كلمة السر أو البريد الإلكتروني.
        /// </summary>
        public static string ErrorMessageLoginWrongEmailOrPassword {
            get {
                return ResourceManager.GetString("ErrorMessageLoginWrongEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string LoginForm {
            get {
                return ResourceManager.GetString("LoginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الدخول بنجاح.
        /// </summary>
        public static string LoginSuccessfull {
            get {
                return ResourceManager.GetString("LoginSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل نسيت كلمة السر؟.
        /// </summary>
        public static string Lostyourpassword {
            get {
                return ResourceManager.GetString("Lostyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string PlaceHolderEmail {
            get {
                return ResourceManager.GetString("PlaceHolderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر.
        /// </summary>
        public static string PlaceHolderPassword {
            get {
                return ResourceManager.GetString("PlaceHolderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string PlaceHolderUserName {
            get {
                return ResourceManager.GetString("PlaceHolderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطا في الاتصال الرجاء إعادة المحاولة مرة ثانية.
        /// </summary>
        public static string ThereIsAProblemTryAgain {
            get {
                return ResourceManager.GetString("ThereIsAProblemTryAgain", resourceCulture);
            }
        }
    }
}
