//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almwdeh.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StudentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Almwdeh.Resources.StudentResource", typeof(StudentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقطع التحصيل.
        /// </summary>
        public static string AcademicDegree {
            get {
                return ResourceManager.GetString("AcademicDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات اضافية.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان في ايران.
        /// </summary>
        public static string AddressIran {
            get {
                return ResourceManager.GetString("AddressIran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان في سوريا.
        /// </summary>
        public static string AddressSyria {
            get {
                return ResourceManager.GetString("AddressSyria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعدل.
        /// </summary>
        public static string AverageScore {
            get {
                return ResourceManager.GetString("AverageScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعدل.
        /// </summary>
        public static string AverageScoreAuto {
            get {
                return ResourceManager.GetString("AverageScoreAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب البنكي.
        /// </summary>
        public static string BankAccountNumber {
            get {
                return ResourceManager.GetString("BankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم البطاقة.
        /// </summary>
        public static string BankCardNumber {
            get {
                return ResourceManager.GetString("BankCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم شبا.
        /// </summary>
        public static string BankShibaNumber {
            get {
                return ResourceManager.GetString("BankShibaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الولادة.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الولادة.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشهادة.
        /// </summary>
        public static string CertificateFile {
            get {
                return ResourceManager.GetString("CertificateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأولاد.
        /// </summary>
        public static string ChildernNumber {
            get {
                return ResourceManager.GetString("ChildernNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة في ايران.
        /// </summary>
        public static string CityIran {
            get {
                return ResourceManager.GetString("CityIran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة في سوريا.
        /// </summary>
        public static string CitySyria {
            get {
                return ResourceManager.GetString("CitySyria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء .
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الواحدات المنتخبة.
        /// </summary>
        public static string CreditAchieved {
            get {
                return ResourceManager.GetString("CreditAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوضع النضباطي.
        /// </summary>
        public static string DisciplineSituation {
            get {
                return ResourceManager.GetString("DisciplineSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المذهب.
        /// </summary>
        public static string Doctrine {
            get {
                return ResourceManager.GetString("Doctrine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم تعديل معلومات الإضافية.
        /// </summary>
        public static string EditExtraInfo {
            get {
                return ResourceManager.GetString("EditExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم تعدیل معلومات الطالب.
        /// </summary>
        public static string EditGeneralInfo {
            get {
                return ResourceManager.GetString("EditGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ تاكييد المعلومات.
        /// </summary>
        public static string EditVerified {
            get {
                return ResourceManager.GetString("EditVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفعالية والنشاط.
        /// </summary>
        public static string EffectivenessAndActivity {
            get {
                return ResourceManager.GetString("EffectivenessAndActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم معلومات إضافية.
        /// </summary>
        public static string ExtraInfo {
            get {
                return ResourceManager.GetString("ExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الأب.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انثى.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        public static string FieldOfStudy {
            get {
                return ResourceManager.GetString("FieldOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم إدخال معلومات المالية.
        /// </summary>
        public static string FinanceInfo {
            get {
                return ResourceManager.GetString("FinanceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوضع المادي.
        /// </summary>
        public static string FinancialStatus {
            get {
                return ResourceManager.GetString("FinancialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السلوك العام.
        /// </summary>
        public static string GeneralBehavior {
            get {
                return ResourceManager.GetString("GeneralBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم إدخال معلومات الطالب.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوضع التحصيلي.
        /// </summary>
        public static string GraduationStatues {
            get {
                return ResourceManager.GetString("GraduationStatues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التخرج.
        /// </summary>
        public static string GraduationYear {
            get {
                return ResourceManager.GetString("GraduationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التعديل.
        /// </summary>
        public static string LastEditDate {
            get {
                return ResourceManager.GetString("LastEditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكنية.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة العائلية.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف في ايران.
        /// </summary>
        public static string MobileIran {
            get {
                return ResourceManager.GetString("MobileIran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف في سوريا.
        /// </summary>
        public static string MobileSyria {
            get {
                return ResourceManager.GetString("MobileSyria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الأم.
        /// </summary>
        public static string MotherName {
            get {
                return ResourceManager.GetString("MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یحتاج مساعدة.
        /// </summary>
        public static string NeedMonthlyAid {
            get {
                return ResourceManager.GetString("NeedMonthlyAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانقضاء.
        /// </summary>
        public static string PassportExpireDate {
            get {
                return ResourceManager.GetString("PassportExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدي اف الجواز.
        /// </summary>
        public static string PassportFile {
            get {
                return ResourceManager.GetString("PassportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم إدخال معلومات جواز السفر.
        /// </summary>
        public static string PassportInfo {
            get {
                return ResourceManager.GetString("PassportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم جواز السفر.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة الشخصية.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهن السابقة.
        /// </summary>
        public static string PreviousJobs {
            get {
                return ResourceManager.GetString("PreviousJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف الشخصي.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الالتزام الديني.
        /// </summary>
        public static string ReligiousCommitment {
            get {
                return ResourceManager.GetString("ReligiousCommitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانقضاء.
        /// </summary>
        public static string ResidentExpireDate {
            get {
                return ResourceManager.GetString("ResidentExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدي اف اقامة.
        /// </summary>
        public static string ResidentFile {
            get {
                return ResourceManager.GetString("ResidentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفصل.
        /// </summary>
        public static string SemesterNumber {
            get {
                return ResourceManager.GetString("SemesterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عائلة شهيد.
        /// </summary>
        public static string ShahidFamily {
            get {
                return ResourceManager.GetString("ShahidFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلة القرابة.
        /// </summary>
        public static string ShahidRelationship {
            get {
                return ResourceManager.GetString("ShahidRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهارات.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ بدء التحصيل.
        /// </summary>
        public static string StartAcademicYearDare {
            get {
                return ResourceManager.GetString("StartAcademicYearDare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم البطاقة الجامعية.
        /// </summary>
        public static string StudentUniversityNum {
            get {
                return ResourceManager.GetString("StudentUniversityNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطا في ادخال المعلومات.
        /// </summary>
        public static string SubmitError {
            get {
                return ResourceManager.GetString("SubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ معلومات بنجاح.
        /// </summary>
        public static string SubmitSucess {
            get {
                return ResourceManager.GetString("SubmitSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعرف.
        /// </summary>
        public static string TheIdentifier {
            get {
                return ResourceManager.GetString("TheIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم إدخال معلومات الجامعة.
        /// </summary>
        public static string UniversityInfo {
            get {
                return ResourceManager.GetString("UniversityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الجامعة.
        /// </summary>
        public static string UniversityName {
            get {
                return ResourceManager.GetString("UniversityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الواتس اب.
        /// </summary>
        public static string WhatsappNumber {
            get {
                return ResourceManager.GetString("WhatsappNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات عن الزوجة.
        /// </summary>
        public static string WifeDetails {
            get {
                return ResourceManager.GetString("WifeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الزوجة.
        /// </summary>
        public static string WifeName {
            get {
                return ResourceManager.GetString("WifeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصیل العمل.
        /// </summary>
        public static string WorkDetails {
            get {
                return ResourceManager.GetString("WorkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یعمل.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
